### ISSUE TITLE
Create a robust shell wrapper for launching Application jar in the embedded mode

### ISSUE THREAD

**Issue by dima767** [UniconLabs/orville#17]
And include this script in the distribution archive in `bin` directory for example. This way it will free users from having to execute long java -jar ... command, will enable the script to be installed as a Linux init.d service or OS X launchd script, etc. This will provide a more production ready operational aspect of the application. Take inspiration from Spring XD starter shell script for example, as at its heart, XD is a Spring Boot app:

https://github.com/spring-projects/spring-xd/blob/master/scripts/xd/xd-singlenode

**Comment by scalding** [comment]
I would put this as a very low priority. Most of those startup scripts do a lot of environment initialization and checking before executing the target, which isn't needed in our instance (and when it is, it's deployment specific). If this sort of robustness is absolutely needed, I would say a WAR deployment is better early on.

**Comment by dima767** [comment]
Well, I'd still would like may be  simpler wrapper script included in the distribution to be able to run as init.d or launchd daemon :-) Not the highest priority, agree, but things like that would make the product `production ready` - whatever that means. Also, if the product is looked at and adopted by the community, it would be nice that folks drive those kind of issues.

**Comment by scalding** [comment]
Yeah, this should be community driven. The first problem you run into when writing init scripts is deciding what type you're going to write and support. SYSV? Upstart? Windows Service? OSX Service? I would imagine that most folks that administer systems would know how to create such a script (or find out how) and could contribute something back.

**Comment by dima767** [comment]
Possibly look at the [Gradle's application plugin](http://www.gradle.org/docs/current/userguide/application_plugin.html) to do this for us
