### ISSUE TITLE
Need a way to bind raw JSON data onto GORM model

### ISSUE THREAD

**Issue by dima767** [UniconLabs/orville#6]
For both new records and existing records (even if incoming JSON data [represented as Map] only holds partial amount of values for the object). If we could use existing GORM's `model.properties = jsonMap` somehow, etc.

http://stackoverflow.com/questions/5806478/binding-only-some-properties-onto-a-grails-domain-object

**Comment by scalding** [comment]
interesting idea, but might be as much work as doing manual binding. In the end, the JSON coming in will be arbitrary rather than standard, so we'll have to provide a mapping configuration similar to what we have for the OR loader now.

**Comment by dima767** [comment]
So at the moment I have no idea how to go about mapping the incoming JSON Maps to both existing and new objects. JSON payload might not contain the entire object graph data in it, etc. So I will leave this part un-implemented
