### ISSUE TITLE
Refactor the pipeline config - get rid of the mock outcome processor

### ISSUE THREAD

**Issue by dima767** [UniconLabs/orville#9]
and make sure the real outcome is set by the idmatch processor

**Comment by scalding** [comment]
Was this done or dropped?

**Comment by dima767** [comment]
Sorry for the confusion. Done. It simply removes the mock outcome processor from the tail end of the pipeline and relies on the idmatch processor to set `ctx.outcome`

https://github.com/UniconLabs/orville/blob/master/web/src/main/groovy/org/apereo/openregistry/Application.groovy#L58

**Comment by scalding** [comment]
ah, so it isn't actually finished since the idMatch processor doesn't actually provide the functionality?

**Comment by dima767** [comment]
Well, you could put it this way, but the issue was to remove the mock outcome - which I did :-) When idmatch provides outcome (good one), well, that'd be good too ;-) If we want to capture that in the diff issue, that's fine.

**Comment by dima767** [comment]
Oh, I see, my first comment on this issue - is what created the confusion. Sorry ;-)

**Comment by scalding** [comment]
I was just concerned that this issue as written removed working functionality.

**Comment by scalding** [comment]
no real worries right now, just want to make sure that we don't break anything that's working with any changes that we make... guess we need to spend a little bit of time working on some integration tests  :-D

**Comment by dima767** [comment]
Not really. That was a real hardcoded mock outcome that had no correlation to the real idmatch processing. So you could consider no working functionality has been removed ;-)

We could put that mock processor back, no problem too ;-)

**Comment by scalding** [comment]
probably my fault since I actually changed the that mock  processor to actually work properly. I'm working on moving all that stuff out to other processors, though.

**Comment by dima767** [comment]
Ah OK. Roger that. No one's fault. No blames :-) I originally created that mock processor to be just that - a hardcoded mock outcome. Did not realize the real outcome was being set there (dynamic one). But, yeah, agree, let's move the real functionality elsewhere and be done with it ;-)

And now it's past my `happy hour` time. I'd better log off ;-)
